# Environment variables keys
GITHUB_AUTH_TOKEN = "GITHUB_AUTH_TOKEN"
REPO = "REPO"
AZURE_OPENAI_APIKEY = "AZURE_OPENAI_APIKEY"
AZURE_OPENAI_ENDPOINT = "AZURE_OPENAI_ENDPOINT"
AZURE_OPENAI_MODEL = "AZURE_OPENAI_MODEL"
AZURE_OPENAI_MODEL_API_VERSION = "AZURE_OPENAI_MODEL_API_VERSION"
PR_SUMMARY = "PR_SUMMARY"
PR_SUGGEST_CHANGES = "PR_SUGGEST_CHANGES"