# Environment variables keys
GITHUB_AUTH_TOKEN = "GITHUB_AUTH_TOKEN"
REPO = "REPO"
EVENT = "EVENT"
AZURE_OPENAI_APIKEY = "AZURE_OPENAI_APIKEY"
AZURE_OPENAI_ENDPOINT = "AZURE_OPENAI_ENDPOINT"
AZURE_OPENAI_MODEL = "AZURE_OPENAI_MODEL"
AZURE_OPENAI_MODEL_API_VERSION = "AZURE_OPENAI_MODEL_API_VERSION"
PR_SUMMARY = "PR_SUMMARY"
PR_SUGGEST_CHANGES = "PR_SUGGEST_CHANGES"

#GitHub API URL
PR_COMMENTS_URL_TEMPLATE = "https://api.github.com/repos/{0}/{1}/pulls/{2}/comments"
PR_DIFF_URL_TEMPLATE = "https://api.github.com/repos/{0}/{1}/compare/{2}...{3}"